# Generated by Django 4.0.4 on 2022-04-24 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0002_alter_book_options_alter_book_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Название темы')),
                ('text', tinymce.models.HTMLField()),
                ('image', models.ImageField(blank=True, upload_to='images/records', verbose_name='Изображение')),
                ('document', models.FileField(blank=True, upload_to='documents/records', verbose_name='Документ')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Название темы')),
                ('image', models.ImageField(blank=True, upload_to='images/topics', verbose_name='Изображение')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['id'], name='id_indexT'),
        ),
        migrations.AddField(
            model_name='record',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='record',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.topic'),
        ),
    ]
