# Generated by Django 4.0.3 on 2022-03-23 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_book_document_book_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'Can read all books')]},
        ),
    ]
