# Generated by Django 4.0.4 on 2022-05-05 13:35

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_record_topic_topic_id_indext_record_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='preview',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Превью'),
        ),
        migrations.AddField(
            model_name='record',
            name='preview',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Превью'),
        ),
        migrations.AlterField(
            model_name='record',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Описание'),
        ),
    ]
