# Generated by Django 4.0.4 on 2022-05-05 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0004_book_preview_record_preview_alter_record_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Название подтемы')),
                ('image', models.ImageField(blank=True, upload_to='images/subtopics', verbose_name='Изображение')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.topic')),
            ],
        ),
        migrations.CreateModel(
            name='SubRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Название темы')),
                ('preview', tinymce.models.HTMLField(blank=True, verbose_name='Превью')),
                ('text', tinymce.models.HTMLField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, upload_to='images/records', verbose_name='Изображение')),
                ('document', models.FileField(blank=True, upload_to='documents/records', verbose_name='Документ')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.subtopic')),
            ],
        ),
    ]
