# Generated by Django 4.0.4 on 2022-06-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_subtopic_author_topic_author_alter_record_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='access_level',
            field=models.IntegerField(choices=[(0, 'Все'), (1, 'Преподаватели'), (2, 'Только я')], default=0, help_text='Кто видит эту запись и имеет к ней доступ', verbose_name='Имеют доступ'),
        ),
        migrations.AddField(
            model_name='subrecord',
            name='access_level',
            field=models.IntegerField(choices=[(0, 'Все'), (1, 'Преподаватели'), (2, 'Только я')], default=0, help_text='Кто видит эту запись и имеет к ней доступ', verbose_name='Имеют доступ'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='access_level',
            field=models.IntegerField(choices=[(0, 'Все'), (1, 'Преподаватели'), (2, 'Только я')], default=0, help_text='Кто видит эту тему и имеет к ней доступ', verbose_name='Имеют доступ'),
        ),
        migrations.AddField(
            model_name='topic',
            name='access_level',
            field=models.IntegerField(choices=[(0, 'Все'), (1, 'Преподаватели'), (2, 'Только я')], default=0, help_text='Кто видит эту тему и имеет к ней доступ', verbose_name='Доступ'),
        ),
    ]
