# Generated by Django 4.0.7 on 2023-03-29 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_record_access_level_subrecord_access_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubRecordFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='documents/subrecords', verbose_name='Доп. документ')),
                ('subrecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='learning.subrecord', verbose_name='Файл')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecordFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='documents/records', verbose_name='Доп. документ')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='learning.record', verbose_name='Файл')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
